// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYDKpXMXPtd38m8qzbNTG6BihPrGJvl2M',
    appId: '1:176716014594:web:5333ee8d5d8300f82b331b',
    messagingSenderId: '176716014594',
    projectId: 'detect-f07fd',
    authDomain: 'detect-f07fd.firebaseapp.com',
    databaseURL: 'https://detect-f07fd-default-rtdb.firebaseio.com',
    storageBucket: 'detect-f07fd.appspot.com',
    measurementId: 'G-SPWRYF35DR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-kXaDP2kMbFhDl4aQYg1QhlQ1cAfhRXc',
    appId: '1:176716014594:android:a480c63b7c6b41f62b331b',
    messagingSenderId: '176716014594',
    projectId: 'detect-f07fd',
    databaseURL: 'https://detect-f07fd-default-rtdb.firebaseio.com',
    storageBucket: 'detect-f07fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAUMWKCshOkYZoxo_hZfKStnzERH7u_mo',
    appId: '1:176716014594:ios:a2204b4bd58710392b331b',
    messagingSenderId: '176716014594',
    projectId: 'detect-f07fd',
    databaseURL: 'https://detect-f07fd-default-rtdb.firebaseio.com',
    storageBucket: 'detect-f07fd.appspot.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAUMWKCshOkYZoxo_hZfKStnzERH7u_mo',
    appId: '1:176716014594:ios:62facd1821f097092b331b',
    messagingSenderId: '176716014594',
    projectId: 'detect-f07fd',
    databaseURL: 'https://detect-f07fd-default-rtdb.firebaseio.com',
    storageBucket: 'detect-f07fd.appspot.com',
    iosBundleId: 'com.example.demo.RunnerTests',
  );
}
